name: 'Net Negative Lines of Code'
description: 'Report the net negative lines of code between releases'
author: 'alexcheuk'
branding:
  icon: 'arrow-down'
  color: 'gray-dark'
inputs:
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  directory:
    description: directory to run cloc
  checkpoint_tag:
    description: checkpoint tag
  checkpoint_title:
    description: checkpoint title
  exclude_dir:
    description: exclude dir
  exclude_ext:
    description: exclude ext
  include_ext:
    description: exclude ext
  slack_webhook:
    description: Slack webhook
  slack_release_diff_breakdown:
    description: Show a breakdown between the current release and the release before that
    default: false
  slack_checkpoint_diff_breakdown:
    description: Show a breakdown between the current release and the release before that
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
